del /S .\log\*.log
mkdir log
curl -vX GET http://localhost:49519/api/dataobject/vms/all  > ./log/vmsAll.log
curl -vX GET http://localhost:49519/api/dataobject/vms/CFB613DE80003254E0433CC411ACFD01  > ./log/vmsId.log
curl -vX GET http://localhost:49519/api/dataobject/vms/count  > ./log/vmsCount.log
curl -vX GET http://localhost:49519/api/dataobject/event/RW-15-04-28-000517 > ./log/eventId.log
curl -vX GET http://localhost:49519/api/dataobject/event/all > ./log/eventAll.log
curl -vX GET http://localhost:49519/api/dataobject/event/count > ./log/eventCount.log
curl -vX GET http://localhost:49519/api/dataobject/anpr/ANPR_Measurement_Site_30072647 > ./log/anprId.log
curl -vX GET http://localhost:49519/api/dataobject/anpr/all > ./log/anprAll.log
curl -vX GET http://localhost:49519/api/dataobject/anpr/count > ./log/anprCount.log
curl -vX GET http://localhost:49519/api/dataobject/fusedFVDAndSensor/TravelTimeData101003501 > ./log/FVDAndSensorId.log
curl -vX GET http://localhost:49519/api/dataobject/fusedFVDAndSensor/all > ./log/FVDAndSensorAll.log
curl -vX GET http://localhost:49519/api/dataobject/fusedFVDAndSensor/count > ./log/FVDAndSensorCount.log
curl -vX GET http://localhost:49519/api/dataobject/fusedSensorOnly/TrafficFlow101003001 > ./log/SensorOnlyId.log
curl -vX GET http://localhost:49519/api/dataobject/fusedSensorOnly/all > ./log/SensorOnlyAll.log
curl -vX GET http://localhost:49519/api/dataobject/fusedSensorOnly/count > ./log/SensorOnlyCount.log
curl -vX GET http://localhost:49519/api/dataobject/midas/7877E1FA9F4B4674BED9E33FA55D3C3B > ./log/midasId.log
curl -vX GET http://localhost:49519/api/dataobject/midas/all > ./log/midasAll.log
curl -vX GET http://localhost:49519/api/dataobject/midas/count > ./log/midasCount.log
curl -vX GET http://localhost:49519/api/dataobject/tmu/C6E971CAD0E0789BE0433CC411ACCCEA > ./log/tmuId.log
curl -vX GET http://localhost:49519/api/dataobject/tmu/all > ./log/tmuAll.log
curl -vX GET http://localhost:49519/api/dataobject/tmu/count > ./log/tmuCount.log
curl -vX GET http://localhost:49519/api/dataobject/vmsStatic/CFB613DE80003254E0433CC411ACFD01 > ./log/vmsStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/vmsStatic/all > ./log/vmsStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/vmsStatic/count > ./log/vmsStaticCount.log
curl -vX GET http://localhost:49519/api/dataobject/matrixSignalStatic/D250950213C17952E0433CC411ACA994 > ./log/matrixStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/matrixSignalStatic/all > ./log/matrisStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/matrixSignalStatic/count > ./log/matrixStaticCount.log
curl -vX GET http://localhost:49519/api/dataobject/tameStatic/C6ED3C02335B3F7DE0433CC411AC7306 > ./log/tameStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/tameStatic/all > ./log/tameStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/tameStatic/count > ./log/tameCount.log
curl -vX GET http://localhost:49519/api/dataobject/midasStatic/7877E1FA9F4B4674BED9E33FA55D3C3B > ./log/midasStaticId.log
--curl -vX GET http://localhost:49519/api/dataobject/midasStatic/all > ./log/midasStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/midasStatic/count > ./log/midasStaticCount.log
curl -vX GET http://localhost:49519/api/dataobject/anprStatic/ANPR_Measurement_Site_3007264718:13 02/01/2016 > ./log/anprStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/anprStatic/all > ./log/anprStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/anprStatic/count > ./log/anprStaticCount.log
curl -vX GET http://localhost:49519/api/dataobject/tmuStatic/C6E971CAD0E0789BE0433CC411ACCCEA > ./log/tmuStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/tmuStatic/all > ./log/tmuStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/tmuStatic/count > ./log/tmuStaticCount.log
curl -vX GET http://localhost:49519/api/dataobject/linkShapeStatic/108041601_1 > ./log/linkShapeId.log
--curl -vX GET http://localhost:49519/api/dataobject/linkShapeStatic/all > ./log/linkShapeAll.log
curl -vX GET http://localhost:49519/api/dataobject/linkShapeStatic/count > ./log/linkShapeCount.log
curl -vX GET http://localhost:49519/api/dataobject/nwkLinkStatic/108015801 > ./log/LinkStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/nwkLinkStatic/all > ./log/LinkStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/nwkLinkStatic/count > ./log/LinkStaticCount.log
curl -vX GET http://localhost:49519/api/dataobject/anprRouteStatic/NTIS_ANPR_Route_30070898_2 > ./log/anprRouteStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/anprRouteStatic/all > ./log/anprRouteStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/anprRouteStatic/count > ./log/anprRouteStaticCount.log
curl -vX GET http://localhost:49519/api/dataobject/hatrisSectionStatic/HS50000023_1 > ./log/hatrisSectionStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/hatrisSectionStatic/all > ./log/hatirsSectionStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/hatrisSectionStatic/count > ./log/hatrisStaticCount.log
curl -vX GET http://localhost:49519/api/dataobject/nwkNodeStatic/1030220 > ./log/nodeStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/nwkNodeStatic/all > ./log/nodeStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/nwkNodeStatic/count > ./log/nodeStaticCount.log
curl -vX GET http://localhost:49519/api/dataobject/alternateRouteStatic/8200002_18 > ./log/alternativeRouteStaticId.log
curl -vX GET http://localhost:49519/api/dataobject/alternateRouteStatic/all > ./log/alternativeRouteStaticAll.log
curl -vX GET http://localhost:49519/api/dataobject/alternateRouteStatic/count  > ./log/alternativeRouteStaticCount.log
